travis:
  secure:
    BINSTAR_TOKEN: jLnwdEy01ETqAFWsosklvKxOw6naLfzrzCoJZDnp292R2UHDoqTKyxGbpdHZeiNsoZKJVdWEvZOzYDhSC1nBIJTRHoO8jKzDW9CHU0MT2NX+2HhTbSWPuNNXrIGmtYs+zKrvEW4s+4Sw4WGDc4D1oMjjc+gYKfw+9j2QqbQOVEE34mGs/L7thQL6o8bYEivflk9rWLWfBkMHIHoUvXYpdQqOXq7YkHf6wnYOHnqbAM2QDFYhxzhQ/juEC9cW8vS6V4zt6+srBZF5AKZt7HjR2KJcdmUyPhNehXWLi39xY8LmXG3dpZnsqTRMM31piNk0MReQht5mRzsffphGk0nZk9yZl4z173jeMHF6f6ZxJHSSO4HRCPzRcKco1gSvbo4nSJt8QYLz5zCgRLTTDBsxBkCdp/gwU2+6qrvP6AmoYEkSThqzZzZqkd9wkv5W3fZAAk6qE22El1Uc9+glEe3gbHSAVODlA5IK8zfX0iu/EtBaYoOz3Rodgl1/emRdFhf5kvgruH+PvjO3ZWZnbYtT7bv2ZFBoN208I8DC+ZCDazAAziQAwouWmVj7CcYZOV2uSLTwghzztPM/2UuYzGFKtV4hMBlsMds+bETfKmMEHRnt2z+1hzwCpcddSja8TaHLCwvmDgGmDbrxarcoQZqcjEmqssftcv9wlFQwrZyS1To=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
